export enum ProductActionTypes {
  FETCH_PRODUCTS = "FETCH_PRODUCTS",
  FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR",

  CREATE_PRODUCT = "CREATE_PRODUCT",
  CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR",

  EDIT_PRODUCT = "EDIT_PRODUCT",
  EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS",
  EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR",

  DELETE_PRODUCT = "DELETE_PRODUCT",
  DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR",
}
